### ISSUE TITLE
Doesn't like SSIDs with single quotes in name

### ISSUE THREAD

**Issue by coxymla** [Bertware/wlan10#12]
One of the SSIDs I have connected to has a single quote in it's name, i.e. `SoAndSo's iPhone SE`.

When I launch wlan10 I get the error:

```
The application encountered an unexpected error while parsing a network. You can continue using the app, but some profiles may be missing. Please report this error to the developer ("http://github.com/Bertware/Wlan10/Issues")

Error details:

Input string was not in a correct format.

   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)

   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)

   at Net.Bertware.Wlan10.Model.WlanNetwork..ctor(String name)



Profile "SoAndSo's iPhoneSE" is not found on the system.
```

**Comment by afit** [comment]
The single quotes aren't the issue, I've tested with both ASCII and smart-quotes. The issue is one of the properties of the network not being parsed properly.

Can you share more detail with us? If you run the following in a shell, it'll dump out the properties that the program is trying to parse:

```
netsh wlan show profiles "SoAndSo's iPhone SE"
```

**Comment by afit** [comment]
That network name of yours contains Unicode: it's not a normal apostrophe. This was fixed with my patch for #8, so I'd guess you're running a precompiled release build rather than source.

@Bertware hasn't shipped a new build that patch, but when he does it'll fix your problem.

If you are running from source and it's still breaking, please let me know.
